Category related code
MilianCode/book-store pull request #10
Opened 2024-07-24 17:37 UTC by MilianCode

2024-07-25 19:31 UTC, Elena-Bruyako requested changes
see comments

2024-07-25 19:31 UTC, Elena-Bruyako commented on src/main/java/com/miliancode/controller/BookController.java
> +    public List<BookDtoWithoutCategotyIds> getAll(
revert to BookDto

2024-07-25 19:31 UTC, Elena-Bruyako commented on src/main/java/com/miliancode/model/Book.java
> +    @ManyToMany(fetch = FetchType.LAZY)
```suggestion
    @ManyToMany
```

2024-07-25 19:31 UTC, Elena-Bruyako commented on src/main/java/com/miliancode/service/impl/CategoryServiceImpl.java
> +        return mapper.toDto(savedCategory);
```suggestion
        return mapper.toDto(categoryRepository.save(category));
```

2024-07-25 19:31 UTC, Elena-Bruyako commented on src/main/java/com/miliancode/service/impl/CategoryServiceImpl.java
> +        category.setId(id);
```suggestion
        Category category = repository.findById(id)
                .orElseThrow(()....
        mapper.updateCategoryFromDto(.....
        return mapper.toDto(categoryRepository.save(category));
```

2024-07-25 19:31 UTC, Elena-Bruyako commented on src/main/java/com/miliancode/service/impl/CategoryServiceImpl.java
> +    @Override
Check where we need Transactional

2024-07-26 19:38 UTC, sarakhmen approved these changes

2024-07-26 22:27 UTC, merged