Implemented JPA and Liquibase
MilianCode/book-store pull request #4
Opened 2024-04-26 16:38 UTC by MilianCode

2024-04-26 17:48 UTC, olekskov requested changes

2024-04-26 17:48 UTC, olekskov commented on src/main/resources/application.properties
> +spring.liquibase.change-log=classpath:db/changelog.yml
You should have here master changelog that includes list of patch-sets in it.
In such way it's easier to maintain them when there are more changes

2024-04-26 17:48 UTC, olekskov commented on src/main/java/com/miliancode/service/impl/BookServiceImpl.java
> +        Book book = bookRepository.findById(id).get();
do not use raw get() on Optional, you make it useless in such way
use orElseThrow()

2024-04-27 05:17 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2024-04-27 05:17 UTC, Elena-Bruyako commented on pom.xml
> +                <version>4.27.0</version>
Redundant, spring-boot-starter-parent provide the version of liquibase

2024-04-27 05:17 UTC, Elena-Bruyako commented on src/main/java/com/miliancode/model/Book.java
> +@Where(clause = "is_deleted=false")
`@Where` is deprecated, use SQLRestriction instead

2024-04-27 05:17 UTC, Elena-Bruyako commented on src/main/java/com/miliancode/model/Book.java
>      private String title;
`@Column(nullable = false)`
add do each required fields (look at HW task)

2024-04-27 05:17 UTC, Elena-Bruyako commented on src/main/java/com/miliancode/service/impl/BookServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("Book not found with id: " + id));
```suggestion
                .orElseThrow(() -> new EntityNotFoundException("Book not found with id: " + id));

```

2024-04-27 05:17 UTC, Elena-Bruyako commented on src/main/java/com/miliancode/service/impl/BookServiceImpl.java
> +        book.setTitle(requestDto.getTitle());
It looks like Mapper should set up Book

2024-04-28 06:06 UTC, Elena-Bruyako approved these changes

2024-05-06 10:20 UTC, merged